In [1]:
import pandas as pd
a=pd.read_csv(r"C:\\COURSES\\DATA SCIENCE\\actual lessons\\Titanic-Dataset.csv")
a

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
#first 5 rows
a.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# last 3 rows
a.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
#column names
a.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
#all data types
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#TASK 2 TASK 2 TASK 2

In [11]:
# creating a data frame
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,55,60,65,70,75,80,85,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10]}
student_scores=pd.DataFrame(student_scores)
student_scores

              Name  Age  Score
0               hi    1     50
1            hallo    2     55
2          bonjour    3     60
3         gutentag    4     65
4             ciao    5     70
5              bye    6     75
6  auf wiedersehen    7     80
7            salut    8     85
8              yes    9     90
9               no   10     95

In [23]:
#names of students with above 80
high_scorers = student_scores[student_scores['Score'] > 80]
high_scorers

    Name  Age  Score
7  salut    8     85
8    yes    9     90
9     no   10     95

In [25]:
print(student_scores[student_scores["Score"]>80])

    Name  Age  Score
7  salut    8     85
8    yes    9     90
9     no   10     95

In [29]:
high_scorers["Name"]

7    salut
8      yes
9       no
Name: Name, dtype: object

In [67]:
#multiple conditions marks>75 and attendance>85
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,55,60,65,70,75,80,85,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","CSE","CSE","English","Math","Physics","Chemistry","Biology","History"]}
student_scores=pd.DataFrame(student_scores)
student_scores
a = student_scores.loc[(student_scores["Score"] > 75)&(student_scores["Attendance"]>85)]
a

              Name  Age  Score  Attendance Department
6  auf wiedersehen    7     80          95    Physics
7            salut    8     85         100  Chemistry
8              yes    9     90         100    Biology

In [63]:
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,55,60,65,70,75,80,85,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","CSE","CSE","English","Math","Physics","Chemistry","Biology","History"]}
student_scores=pd.DataFrame(student_scores)
CSE=student_scores.loc[student_scores["Department"]=="CSE",["Name","Department","Score"]]
#CSE=student_scores[student_scores["Name","Department","Score"]Department="CSE"]
CSE

       Name Department  Score
0        hi        CSE     50
1     hallo        CSE     55
2   bonjour        CSE     60
3  gutentag        CSE     65

In [81]:
# sorting values
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,55,60,65,70,75,80,85,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","CSE","CSE","English","Math","Physics","Chemistry","Biology","History"]}
student_scores=pd.DataFrame(student_scores)
student_scores
sorted=student_scores.sort_values(by="Score")
sorted
sorted.tail(3)

    Name  Age  Score  Attendance Department
7  salut    8     85         100  Chemistry
8    yes    9     90         100    Biology
9     no   10     95          10    History

In [85]:
#create new column
student_scores=student_scores.assign(Results=["","","","","","","","","",""])
student_scores

              Name  Age  Score  Attendance Department Results
0               hi    1     50          70        CSE
1            hallo    2     55          75        CSE
2          bonjour    3     60          80        CSE
3         gutentag    4     65          85        CSE
4             ciao    5     70          90    English
5              bye    6     75          65       Math
6  auf wiedersehen    7     80          95    Physics
7            salut    8     85         100  Chemistry
8              yes    9     90         100    Biology
9               no   10     95          10    History

In [91]:
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,45,60,25,70,75,80,15,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","CSE","CSE","English","Math","Physics","Chemistry","Biology","History"]}
student_scores=pd.DataFrame(student_scores)
student_scores
student_scores.loc[student_scores['Score'] >= 50, 'Result'] = 'Pass'
student_scores.loc[student_scores['Score'] < 50, 'Result'] = 'Fail'
student_scores

              Name  Age  Score  Attendance Department Result
0               hi    1     50          70        CSE   Pass
1            hallo    2     45          75        CSE   Fail
2          bonjour    3     60          80        CSE   Pass
3         gutentag    4     25          85        CSE   Fail
4             ciao    5     70          90    English   Pass
5              bye    6     75          65       Math   Pass
6  auf wiedersehen    7     80          95    Physics   Pass
7            salut    8     15         100  Chemistry   Fail
8              yes    9     90         100    Biology   Pass
9               no   10     95          10    History   Pass

In [97]:
#CREATING THE GRADES COLUMN
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,45,60,25,70,75,80,15,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","CSE","CSE","English","Math","Physics","Chemistry","Biology","History"]}
student_scores=pd.DataFrame(student_scores)
student_scores
student_scores.loc[student_scores['Score'] < 60, 'Grade'] = 'F'
student_scores.loc[student_scores['Score'] >= 60, 'Grade'] = 'C'
student_scores.loc[student_scores['Score'] >= 70, 'Grade'] = 'B'
student_scores.loc[student_scores['Score'] >= 80, 'Grade'] = 'A'
student_scores.loc[student_scores['Score'] >= 90, 'Grade'] = 'A+'
student_scores

              Name  Age  Score  Attendance Department Grade
0               hi    1     50          70        CSE     F
1            hallo    2     45          75        CSE     F
2          bonjour    3     60          80        CSE     C
3         gutentag    4     25          85        CSE     F
4             ciao    5     70          90    English     B
5              bye    6     75          65       Math     B
6  auf wiedersehen    7     80          95    Physics     A
7            salut    8     15         100  Chemistry     F
8              yes    9     90         100    Biology    A+
9               no   10     95          10    History    A+

In [119]:
import pandas as pd
student_scores= {"Name": ["hi","hallo","bonjour","gutentag","ciao","bye","auf wiedersehen","salut","yes","no"],
                "Age": [1,2,3,4,5,6,7,8,9,10],
                "Score":[50,45,60,25,70,75,80,15,90,95],
                "Attendance":[70,75,80,85,90,65,95,100,100,10],
                "Department":["CSE","CSE","Chemistry","CSE","English","Math","Physics","Chemistry","Biology","CSE"]}
student_scores=pd.DataFrame(student_scores)
student_scores
#student_scores.groupby("Department").mean("Score")
student_scores.groupby("Department")["Score"].mean()

Department
Biology      90.00
CSE          53.75
Chemistry    37.50
English      70.00
Math         75.00
Physics      80.00
Name: Score, dtype: float64

In [121]:
student_scores.groupby("Department")["Attendance"].mean()

Department
Biology      100.0
CSE           60.0
Chemistry     90.0
English       90.0
Math          65.0
Physics       95.0
Name: Attendance, dtype: float64

In [123]:
student_scores.groupby("Department").mean("Score")

             Age  Score  Attendance
Department
Biology     9.00  90.00       100.0
CSE         4.25  53.75        60.0
Chemistry   5.50  37.50        90.0
English     5.00  70.00        90.0
Math        6.00  75.00        65.0
Physics     7.00  80.00        95.0

In [143]:
student_scores.groupby("Department")["Name"]["Score"].max()

IndexError: Column(s) Name already selected